/**
 * 動漫題庫（圖案／純聲音 ↔ 假名／羅馬拼音／文字）
 * 作品：咒術迴戰、七龍珠、航海王。
 * 圖示為非官方學習插圖／暫用象徵圖，非官方立繪。
 */
window.JPMatchAnime = (() => {
  const ENTRIES = [
    // —— 咒術迴戰：人物 ——
    {
      key: "jjk_itadori",
      series: "jjk",
      hira: "いたどりゆうじ",
      romaji: "itadoriyuuji",
      pic: "assets/icons/anime/jjk/itadori.webp",
      label: "虎杖悠仁",
      kanji: "虎杖悠仁",
      picKind: "img",
      tts: "いたどりゆうじ",
    },
    {
      key: "jjk_fushiguro",
      series: "jjk",
      hira: "ふしぐろめぐみ",
      romaji: "fushiguromegumi",
      pic: "assets/icons/anime/jjk/fushiguro.webp",
      label: "伏黒恵",
      kanji: "伏黒恵",
      picKind: "img",
      tts: "ふしぐろめぐみ",
    },
    {
      key: "jjk_kugisaki",
      series: "jjk",
      hira: "くぎさきのばら",
      romaji: "kugisakinobara",
      pic: "assets/icons/anime/jjk/kugisaki.webp",
      label: "釘崎野薔薇",
      kanji: "釘崎野薔薇",
      picKind: "img",
      tts: "くぎさきのばら",
    },
    {
      key: "jjk_gojou",
      series: "jjk",
      hira: "ごじょうさとる",
      romaji: "gojousatoru",
      pic: "assets/icons/anime/jjk/gojou.webp",
      label: "五条悟",
      kanji: "五条悟",
      picKind: "img",
      tts: "ごじょうさとる",
    },
    {
      key: "jjk_getou",
      series: "jjk",
      hira: "げとうすぐる",
      romaji: "getousuguru",
      pic: "assets/icons/anime/jjk/getou.webp",
      label: "夏油傑",
      kanji: "夏油傑",
      picKind: "img",
      tts: "げとうすぐる",
    },
    {
      key: "jjk_sukuna",
      series: "jjk",
      hira: "りょうめんすくな",
      romaji: "ryoumensukuna",
      pic: "assets/icons/anime/jjk/sukuna.webp",
      label: "両面宿儺",
      kanji: "両面宿儺",
      picKind: "img",
      tts: "りょうめんすくな",
    },
    {
      key: "jjk_maki",
      series: "jjk",
      hira: "ぜんいんまき",
      romaji: "zeninmaki",
      pic: "assets/icons/anime/jjk/maki.webp",
      label: "禪院真希",
      kanji: "禅院真希",
      picKind: "img",
      tts: "ぜんいんまき",
    },
    {
      key: "jjk_inumaki",
      series: "jjk",
      hira: "いぬまきとげ",
      romaji: "inumakitoge",
      pic: "assets/icons/anime/jjk/inumaki.webp",
      label: "狗巻棘",
      kanji: "狗巻棘",
      picKind: "img",
      tts: "いぬまきとげ",
    },
    {
      key: "jjk_panda",
      series: "jjk",
      hira: "パンダ",
      romaji: "panda",
      pic: "assets/icons/anime/jjk/panda.webp",
      label: "熊貓",
      kanji: "パンダ",
      picKind: "img",
      tts: "パンダ",
    },
    {
      key: "jjk_nanami",
      series: "jjk",
      hira: "ななみけんと",
      romaji: "nanamikento",
      pic: "assets/icons/anime/jjk/nanami.webp",
      label: "七海建人",
      kanji: "七海建人",
      picKind: "img",
      tts: "ななみけんと",
    },
    {
      key: "jjk_toudou",
      series: "jjk",
      hira: "とうどうあおい",
      romaji: "toudouaoi",
      pic: "assets/icons/anime/jjk/toudou.webp",
      label: "東堂葵",
      kanji: "東堂葵",
      picKind: "img",
      tts: "とうどうあおい",
    },
    {
      key: "jjk_okkotsu",
      series: "jjk",
      hira: "おっこつゆうた",
      romaji: "okkotsuyuuta",
      pic: "assets/icons/anime/jjk/okkotsu.webp",
      label: "乙骨憂太",
      kanji: "乙骨憂太",
      picKind: "img",
      tts: "おっこつゆうた",
    },
    {
      key: "jjk_rika",
      series: "jjk",
      hira: "りか",
      romaji: "rika",
      pic: "assets/icons/anime/jjk/rika.webp",
      label: "里香",
      kanji: "里香",
      picKind: "img",
      tts: "りか",
    },
    {
      key: "jjk_meimei",
      series: "jjk",
      hira: "めいめい",
      romaji: "meimei",
      pic: "assets/icons/anime/jjk/meimei.webp",
      label: "冥冥",
      kanji: "冥冥",
      picKind: "img",
      tts: "めいめい",
    },
    {
      key: "jjk_ieiri",
      series: "jjk",
      hira: "いえいりしょうこ",
      romaji: "ieirishouko",
      pic: "assets/icons/anime/jjk/ieiri.webp",
      label: "家入硝子",
      kanji: "家入硝子",
      picKind: "img",
      tts: "いえいりしょうこ",
    },
    {
      key: "jjk_chousou",
      series: "jjk",
      hira: "ちょうそう",
      romaji: "chousou",
      pic: "assets/icons/anime/jjk/chousou.webp",
      label: "脹相",
      kanji: "脹相",
      picKind: "img",
      tts: "ちょうそう",
    },
    {
      key: "jjk_mahito",
      series: "jjk",
      hira: "まひと",
      romaji: "mahito",
      pic: "assets/icons/anime/jjk/mahito.webp",
      label: "真人",
      kanji: "真人",
      picKind: "img",
      tts: "まひと",
    },
    {
      key: "jjk_jougo",
      series: "jjk",
      hira: "じょうご",
      romaji: "jougo",
      pic: "assets/icons/anime/jjk/jougo.webp",
      label: "漏瑚",
      kanji: "漏瑚",
      picKind: "img",
      tts: "じょうご",
    },
    {
      key: "jjk_hanami",
      series: "jjk",
      hira: "はなみ",
      romaji: "hanami",
      pic: "assets/icons/anime/jjk/hanami.webp",
      label: "花御",
      kanji: "花御",
      picKind: "img",
      tts: "はなみ",
    },

    // —— 咒術迴戰：招式／術語 ——
    {
      key: "jjk_ryouiki",
      series: "jjk",
      hira: "りょういきてんかい",
      romaji: "ryouikitenkai",
      pic: "assets/icons/anime/jjk/ryouiki.webp",
      label: "領域展開",
      kanji: "領域展開",
      picKind: "img",
      tts: "りょういきてんかい",
    },
    {
      key: "jjk_muryoukuusho",
      series: "jjk",
      hira: "むりょうくうしょ",
      romaji: "muryoukuusho",
      pic: "assets/icons/anime/jjk/muryoukuusho.webp",
      label: "無量空処",
      kanji: "無量空処",
      picKind: "img",
      tts: "むりょうくうしょ",
    },
    {
      key: "jjk_fukumamizushi",
      series: "jjk",
      hira: "ふくまみづし",
      romaji: "fukumamizushi",
      pic: "assets/icons/anime/jjk/fukumamizushi.webp",
      label: "伏魔御厨子",
      kanji: "伏魔御厨子",
      picKind: "img",
      tts: "ふくまみづし",
    },
    {
      key: "jjk_tokusa",
      series: "jjk",
      hira: "とくさのかげぼうじゅつ",
      romaji: "tokusanokageboujutsu",
      pic: "assets/icons/anime/jjk/tokusa.webp",
      label: "十種影法術",
      kanji: "十種影法術",
      picKind: "img",
      tts: "とくさのかげぼうじゅつ",
    },
    {
      key: "jjk_kokusen",
      series: "jjk",
      hira: "こくせん",
      romaji: "kokusen",
      pic: "assets/icons/anime/jjk/kokusen.webp",
      label: "黒閃",
      kanji: "黒閃",
      picKind: "img",
      tts: "こくせん",
    },
    {
      key: "jjk_ao",
      series: "jjk",
      hira: "あお",
      romaji: "ao",
      pic: "assets/icons/anime/jjk/ao.webp",
      label: "蒼",
      kanji: "蒼",
      picKind: "img",
      tts: "あお",
    },
    {
      key: "jjk_aka",
      series: "jjk",
      hira: "あか",
      romaji: "aka",
      pic: "assets/icons/anime/jjk/aka.webp",
      label: "赫",
      kanji: "赫",
      picKind: "img",
      tts: "あか",
    },
    {
      key: "jjk_murasaki",
      series: "jjk",
      hira: "むらさき",
      romaji: "murasaki",
      pic: "assets/icons/anime/jjk/murasaki.webp",
      label: "茈",
      kanji: "茈",
      picKind: "img",
      tts: "むらさき",
    },
    {
      key: "jjk_toji",
      series: "jjk",
      hira: "ふしぐろとうじ",
      romaji: "fushigurotoji",
      pic: "assets/icons/anime/jjk/toji.webp",
      label: "伏黑甚爾",
      kanji: "伏黒甚爾",
      picKind: "img",
      tts: "ふしぐろとうじ",
    },
    {
      key: "jjk_higuruma",
      series: "jjk",
      hira: "ひぐるまひろみ",
      romaji: "higurumahiromi",
      pic: "assets/icons/anime/jjk/higuruma.webp",
      label: "日車寬見",
      kanji: "日車寛見",
      picKind: "img",
      tts: "ひぐるまひろみ",
    },
    {
      key: "jjk_naoya",
      series: "jjk",
      hira: "ぜんいんなおや",
      romaji: "zeninnaoya",
      pic: "assets/icons/anime/jjk/naoya.webp",
      label: "禪院直哉",
      kanji: "禅院直哉",
      picKind: "img",
      tts: "ぜんいんなおや",
    },
    {
      key: "jjk_tobari",
      series: "jjk",
      hira: "とばり",
      romaji: "tobari",
      pic: "assets/icons/anime/jjk/tobari.webp",
      label: "帳",
      kanji: "帳",
      picKind: "img",
      tts: "とばり",
    },

    // —— 七龍珠：人物 ——
    {
      key: "db_goku",
      series: "db",
      hira: "そんごくう",
      romaji: "songokuu",
      pic: "assets/icons/anime/db/goku.webp",
      label: "孫悟空",
      kanji: "孫悟空",
      picKind: "img",
      tts: "そんごくう",
    },
    {
      key: "db_vegeta",
      series: "db",
      hira: "ベジータ",
      romaji: "bejiita",
      pic: "assets/icons/anime/db/vegeta.webp",
      label: "達爾",
      kanji: "ベジータ",
      picKind: "img",
      tts: "べじーた",
    },
    {
      key: "db_bulma",
      series: "db",
      hira: "ブルマ",
      romaji: "buruma",
      pic: "assets/icons/anime/db/bulma.webp",
      label: "布瑪",
      kanji: "ブルマ",
      picKind: "img",
      tts: "ぶるま",
    },
    {
      key: "db_piccolo",
      series: "db",
      hira: "ピッコロ",
      romaji: "pikkoro",
      pic: "assets/icons/anime/db/piccolo.webp",
      label: "比克",
      kanji: "ピッコロ",
      picKind: "img",
      tts: "ぴっころ",
    },
    {
      key: "db_kuririn",
      series: "db",
      hira: "クリリン",
      romaji: "kuririn",
      pic: "assets/icons/anime/db/kuririn.webp",
      label: "克林",
      kanji: "クリリン",
      picKind: "img",
      tts: "くりりん",
    },
    {
      key: "db_yamcha",
      series: "db",
      hira: "ヤムチャ",
      romaji: "yamucha",
      pic: "assets/icons/anime/db/yamcha.webp",
      label: "亞姆查",
      kanji: "ヤムチャ",
      picKind: "img",
      tts: "やむちゃ",
    },
    {
      key: "db_tenshinhan",
      series: "db",
      hira: "テンシンハン",
      romaji: "tenshinhan",
      pic: "assets/icons/anime/db/tenshinhan.webp",
      label: "天津飯",
      kanji: "天津飯",
      picKind: "img",
      tts: "てんしんはん",
    },
    {
      key: "db_chaozu",
      series: "db",
      hira: "チャオズ",
      romaji: "chaozu",
      pic: "assets/icons/anime/db/chaozu.webp",
      label: "餃子",
      kanji: "餃子",
      picKind: "img",
      tts: "チャオズ",
    },
    {
      key: "db_gohan",
      series: "db",
      hira: "そんごはん",
      romaji: "songohan",
      pic: "assets/icons/anime/db/gohan.webp",
      label: "孫悟飯",
      kanji: "孫悟飯",
      picKind: "img",
      tts: "そんごはん",
    },
    {
      key: "db_trunks",
      series: "db",
      hira: "トランクス",
      romaji: "torankusu",
      pic: "assets/icons/anime/db/trunks.webp",
      label: "特南克斯",
      kanji: "トランクス",
      picKind: "img",
      tts: "とらんくす",
    },
    {
      key: "db_goten",
      series: "db",
      hira: "そんごてん",
      romaji: "songoten",
      pic: "assets/icons/anime/db/goten.webp",
      label: "孫悟天",
      kanji: "孫悟天",
      picKind: "img",
      tts: "そんごてん",
    },
    {
      key: "db_videl",
      series: "db",
      hira: "ビーデル",
      romaji: "biideru",
      pic: "assets/icons/anime/db/videl.webp",
      label: "比迪麗",
      kanji: "ビーデル",
      picKind: "img",
      tts: "びーでる",
    },
    {
      key: "db_chichi",
      series: "db",
      hira: "チチ",
      romaji: "chichi",
      pic: "assets/icons/anime/db/chichi.webp",
      label: "琪琪",
      kanji: "チチ",
      picKind: "img",
      tts: "ちち",
    },
    {
      key: "db_kamesennin",
      series: "db",
      hira: "カメセンニン",
      romaji: "kamesennin",
      pic: "assets/icons/anime/db/kamesennin.webp",
      label: "龜仙人",
      kanji: "亀仙人",
      picKind: "img",
      tts: "かめせんにん",
    },
    {
      key: "db_frieza",
      series: "db",
      hira: "フリーザ",
      romaji: "furiiza",
      pic: "assets/icons/anime/db/frieza.webp",
      label: "弗利沙",
      kanji: "フリーザ",
      picKind: "img",
      tts: "ふりーざ",
    },
    {
      key: "db_cell",
      series: "db",
      hira: "セル",
      romaji: "seru",
      pic: "assets/icons/anime/db/cell.webp",
      label: "賽魯",
      kanji: "セル",
      picKind: "img",
      tts: "せる",
    },
    {
      key: "db_buu",
      series: "db",
      hira: "マジンブウ",
      romaji: "majinbuu",
      pic: "assets/icons/anime/db/buu.webp",
      label: "魔人普烏",
      kanji: "魔人ブウ",
      picKind: "img",
      tts: "まじんぶう",
    },
    {
      key: "db_bardock",
      series: "db",
      hira: "バーダック",
      romaji: "baadakku",
      pic: "assets/icons/anime/db/bardock.webp",
      label: "巴達克",
      kanji: "バーダック",
      picKind: "img",
      tts: "ばーだっく",
    },
    {
      key: "db_raditz",
      series: "db",
      hira: "ラディッツ",
      romaji: "radittsu",
      pic: "assets/icons/anime/db/raditz.webp",
      label: "拉帝茲",
      kanji: "ラディッツ",
      picKind: "img",
      tts: "らでぃっつ",
    },
    {
      key: "db_nappa",
      series: "db",
      hira: "ナッパ",
      romaji: "nappa",
      pic: "assets/icons/anime/db/nappa.webp",
      label: "那巴",
      kanji: "ナッパ",
      picKind: "img",
      tts: "なっぱ",
    },
    {
      key: "db_ginyu",
      series: "db",
      hira: "ギニュー",
      romaji: "ginyuu",
      pic: "assets/icons/anime/db/ginyu.webp",
      label: "基紐",
      kanji: "ギニュー",
      picKind: "img",
      tts: "ぎにゅー",
    },
    {
      key: "db_android18",
      series: "db",
      hira: "ジュウハチゴウ",
      romaji: "juuhachigou",
      pic: "assets/icons/anime/db/android18.webp",
      label: "人造人18號",
      kanji: "十八号",
      picKind: "img",
      tts: "じゅうはちごう",
    },
    {
      key: "db_beerus",
      series: "db",
      hira: "ビルス",
      romaji: "birusu",
      pic: "assets/icons/anime/db/beerus.webp",
      label: "比魯斯",
      kanji: "ビルス",
      picKind: "img",
      tts: "びるす",
    },
    {
      key: "db_whis",
      series: "db",
      hira: "ウイス",
      romaji: "uisu",
      pic: "assets/icons/anime/db/whis.webp",
      label: "維斯",
      kanji: "ウイス",
      picKind: "img",
      tts: "ういす",
    },
    {
      key: "db_broly",
      series: "db",
      hira: "ブロリー",
      romaji: "burorii",
      pic: "assets/icons/anime/db/broly.webp",
      label: "布洛利",
      kanji: "ブロリー",
      picKind: "img",
      tts: "ぶろりー",
    },

    // —— 七龍珠：人物／型態／物件 ——
    {
      key: "db_kaiou",
      series: "db",
      hira: "カイオウ",
      romaji: "kaiou",
      pic: "assets/icons/anime/db/kaiou.webp",
      label: "界王",
      kanji: "界王",
      picKind: "img",
      tts: "かいおう",
    },
    {
      key: "db_satan",
      series: "db",
      hira: "ミスター・サタン",
      romaji: "misutaasatan",
      pic: "assets/icons/anime/db/satan.webp",
      label: "撒旦",
      kanji: "ミスター・サタン",
      picKind: "img",
      tts: "みすたー・さたん",
    },
    {
      key: "db_supersaiyan",
      series: "db",
      hira: "スーパーサイヤジン",
      romaji: "suupaasaiyajin",
      pic: "assets/icons/anime/db/supersaiyan.webp",
      label: "超級賽亞人",
      kanji: "スーパーサイヤ人",
      picKind: "img",
      tts: "すーぱーさいやじん",
    },
    {
      key: "db_shenron",
      series: "db",
      hira: "シェンロン",
      romaji: "shenron",
      pic: "assets/icons/anime/db/shenron.webp",
      label: "神龍",
      kanji: "神龍",
      picKind: "img",
      tts: "シェンロン",
    },
    {
      key: "db_dragonball",
      series: "db",
      hira: "ドラゴンボール",
      romaji: "doragonbooru",
      pic: "assets/icons/anime/db/dragonball.webp",
      label: "龍珠",
      kanji: "ドラゴンボール",
      picKind: "img",
      tts: "ドラゴンボール",
    },

    // —— 航海王：人物 ——
    {
      key: "op_luffy",
      series: "op",
      hira: "るふぃ",
      romaji: "rufi",
      pic: "assets/icons/anime/op/luffy.png",
      label: "魯夫",
      kanji: "ルフィ",
      picKind: "img",
      tts: "るふぃ",
    },
    {
      key: "op_zoro",
      series: "op",
      hira: "ぞろ",
      romaji: "zoro",
      pic: "assets/icons/anime/op/zoro.png",
      label: "索隆",
      kanji: "ゾロ",
      picKind: "img",
      tts: "ぞろ",
    },
    {
      key: "op_nami",
      series: "op",
      hira: "なみ",
      romaji: "nami",
      pic: "assets/icons/anime/op/nami.png",
      label: "娜美",
      kanji: "ナミ",
      picKind: "img",
      tts: "なみ",
    },
    {
      key: "op_usopp",
      series: "op",
      hira: "うそっぷ",
      romaji: "usoppu",
      pic: "assets/icons/anime/op/usopp.png",
      label: "騙人布",
      kanji: "ウソップ",
      picKind: "img",
      tts: "うそっぷ",
    },
    {
      key: "op_sanji",
      series: "op",
      hira: "さんじ",
      romaji: "sanji",
      pic: "assets/icons/anime/op/sanji.png",
      label: "香吉士",
      kanji: "サンジ",
      picKind: "img",
      tts: "さんじ",
    },
    {
      key: "op_chopper",
      series: "op",
      hira: "ちょっぱー",
      romaji: "choppaa",
      pic: "assets/icons/anime/op/chopper.png",
      label: "喬巴",
      kanji: "チョッパー",
      picKind: "img",
      tts: "ちょっぱー",
    },
    {
      key: "op_robin",
      series: "op",
      hira: "ろびん",
      romaji: "robin",
      pic: "assets/icons/anime/op/robin.png",
      label: "羅賓",
      kanji: "ロビン",
      picKind: "img",
      tts: "ろびん",
    },
    {
      key: "op_franky",
      series: "op",
      hira: "ふらんきー",
      romaji: "furankii",
      pic: "assets/icons/anime/op/franky.png",
      label: "佛朗基",
      kanji: "フランキー",
      picKind: "img",
      tts: "ふらんきー",
    },
    {
      key: "op_brook",
      series: "op",
      hira: "ぶるっく",
      romaji: "burukku",
      pic: "assets/icons/anime/op/brook.png",
      label: "布魯克",
      kanji: "ブルック",
      picKind: "img",
      tts: "ぶるっく",
    },
    {
      key: "op_jinbe",
      series: "op",
      hira: "じんべえ",
      romaji: "jinbee",
      pic: "assets/icons/anime/op/jinbe.png",
      label: "甚平",
      kanji: "ジンベエ",
      picKind: "img",
      tts: "じんべえ",
    },
    {
      key: "op_shanks",
      series: "op",
      hira: "しゃんくす",
      romaji: "shankusu",
      pic: "assets/icons/anime/op/shanks.png",
      label: "香克斯",
      kanji: "シャンクス",
      picKind: "img",
      tts: "しゃんくす",
    },
    {
      key: "op_ace",
      series: "op",
      hira: "えーす",
      romaji: "eesu",
      pic: "assets/icons/anime/op/ace.png",
      label: "艾斯",
      kanji: "エース",
      picKind: "img",
      tts: "えーす",
    },
    {
      key: "op_sabo",
      series: "op",
      hira: "さぼ",
      romaji: "sabo",
      pic: "assets/icons/anime/op/sabo.png",
      label: "薩波",
      kanji: "サボ",
      picKind: "img",
      tts: "さぼ",
    },
    {
      key: "op_law",
      series: "op",
      hira: "ろー",
      romaji: "roo",
      pic: "assets/icons/anime/op/law.png",
      label: "羅",
      kanji: "ロー",
      picKind: "img",
      tts: "ろー",
    },
    {
      key: "op_hancock",
      series: "op",
      hira: "はんこっく",
      romaji: "hankokku",
      pic: "assets/icons/anime/op/hancock.png",
      label: "漢考克",
      kanji: "ハンコック",
      picKind: "img",
      tts: "はんこっく",
    },
    {
      key: "op_crocodile",
      series: "op",
      hira: "くろこだいる",
      romaji: "kurokodairu",
      pic: "assets/icons/anime/op/crocodile.png",
      label: "克洛克達爾",
      kanji: "クロコダイル",
      picKind: "img",
      tts: "くろこだいる",
    },
    {
      key: "op_doflamingo",
      series: "op",
      hira: "どふらみんご",
      romaji: "dofuramingo",
      pic: "assets/icons/anime/op/doflamingo.png",
      label: "多佛朗明哥",
      kanji: "ドフラミンゴ",
      picKind: "img",
      tts: "どふらみんご",
    },
    {
      key: "op_kaido",
      series: "op",
      hira: "かいどう",
      romaji: "kaidou",
      pic: "assets/icons/anime/op/kaido.png",
      label: "凱多",
      kanji: "カイドウ",
      picKind: "img",
      tts: "かいどう",
    },
    {
      key: "op_bigmom",
      series: "op",
      hira: "ビッグマム",
      romaji: "biggumamu",
      pic: "assets/icons/anime/op/bigmom.png",
      label: "大媽",
      kanji: "ビッグ・マム",
      picKind: "img",
      tts: "ビッグマム",
    },
    {
      key: "op_whitebeard",
      series: "op",
      hira: "しろひげ",
      romaji: "shirohige",
      pic: "assets/icons/anime/op/whitebeard.png",
      label: "白鬍子",
      kanji: "白ひげ",
      picKind: "img",
      tts: "しろひげ",
    },
    {
      key: "op_blackbeard",
      series: "op",
      hira: "くろひげ",
      romaji: "kurohige",
      pic: "assets/icons/anime/op/blackbeard.png",
      label: "黑鬍子",
      kanji: "黒ひげ",
      picKind: "img",
      tts: "くろひげ",
    },
    {
      key: "op_mihawk",
      series: "op",
      hira: "みほーく",
      romaji: "mihooku",
      pic: "assets/icons/anime/op/mihawk.png",
      label: "鷹眼",
      kanji: "ミホーク",
      picKind: "img",
      tts: "みほーく",
    },
    {
      key: "op_buggy",
      series: "op",
      hira: "ばぎー",
      romaji: "bagii",
      pic: "assets/icons/anime/op/buggy.png",
      label: "巴基",
      kanji: "バギー",
      picKind: "img",
      tts: "ばぎー",
    },
    {
      key: "op_rayleigh",
      series: "op",
      hira: "れいりー",
      romaji: "reirii",
      pic: "assets/icons/anime/op/rayleigh.png",
      label: "雷利",
      kanji: "レイリー",
      picKind: "img",
      tts: "れいりー",
    },
    {
      key: "op_garp",
      series: "op",
      hira: "がーぷ",
      romaji: "gaapu",
      pic: "assets/icons/anime/op/garp.png",
      label: "卡普",
      kanji: "ガープ",
      picKind: "img",
      tts: "がーぷ",
    },

    // —— 航海王：招式／物件 ——
    {
      key: "op_gomugomu",
      series: "op",
      hira: "ごむごむのみ",
      romaji: "gomugomunomi",
      pic: "assets/icons/anime/op/gomugomu.png",
      label: "橡膠果實",
      kanji: "ゴムゴムの実",
      picKind: "img",
      tts: "ごむごむのみ",
    },
    {
      key: "op_gearsecond",
      series: "op",
      hira: "ぎあせかんど",
      romaji: "giasekando",
      pic: "assets/icons/anime/op/gearsecond.png",
      label: "二檔",
      kanji: "ギア2",
      picKind: "img",
      tts: "ぎあせかんど",
    },
    {
      key: "op_santouryuu",
      series: "op",
      hira: "さんとうりゅう",
      romaji: "santouryuu",
      pic: "assets/icons/anime/op/santouryuu.png",
      label: "三刀流",
      kanji: "三刀流",
      picKind: "img",
      tts: "さんとうりゅう",
    },
    {
      key: "op_haki",
      series: "op",
      hira: "はき",
      romaji: "haki",
      pic: "assets/icons/anime/op/haki.png",
      label: "霸氣",
      kanji: "覇気",
      picKind: "img",
      tts: "はき",
    },
    {
      key: "op_thousandsunny",
      series: "op",
      hira: "サウザンドサニーごう",
      romaji: "sauzandosaniigou",
      pic: "assets/icons/anime/op/thousandsunny.png",
      label: "千陽號",
      kanji: "サウザンドサニー号",
      picKind: "img",
      tts: "サウザンドサニーごう",
    },
  ];

  const SERIES = [
    { id: "jjk", label: "咒術迴戰" },
    { id: "db", label: "七龍珠" },
    { id: "op", label: "航海王" },
  ];

  const DEFAULT_SERIES = "jjk";

  const PAIR_MODES = {
    "pic-hira": {
      id: "pic-hira",
      label: "圖案 ↔ 假名",
      sides: ["pic", "hira"],
      sideLabels: { pic: "圖案", hira: "假名" },
    },
    "pic-romaji": {
      id: "pic-romaji",
      label: "圖案 ↔ 羅馬拼音",
      sides: ["pic", "romaji"],
      sideLabels: { pic: "圖案", romaji: "羅馬拼音" },
    },
    "kanji-hira": {
      id: "kanji-hira",
      label: "漢字名 ↔ 假名",
      sides: ["kanji", "hira"],
      sideLabels: { kanji: "漢字名", hira: "假名" },
    },
    "audio-pic": {
      id: "audio-pic",
      label: "純聲音 ↔ 圖片",
      sides: ["audio", "pic"],
      sideLabels: { audio: "純聲音卡", pic: "圖片" },
    },
    "audio-text": {
      id: "audio-text",
      label: "純聲音 ↔ 文字",
      sides: ["audio", "kanji"],
      sideLabels: { audio: "純聲音卡", kanji: "文字" },
    },
  };

  function shuffle(array) {
    const arr = array.slice();
    for (let i = arr.length - 1; i > 0; i -= 1) {
      const j = Math.floor(Math.random() * (i + 1));
      const tmp = arr[i];
      arr[i] = arr[j];
      arr[j] = tmp;
    }
    return arr;
  }

  function getEntriesInSeries(seriesId) {
    if (!seriesId) return ENTRIES.slice();
    return ENTRIES.filter((entry) => entry.series === seriesId);
  }

  function buildDeck(pairModeId, pairCount, options) {
    const mode = PAIR_MODES[pairModeId];
    if (!mode) throw new Error("未知動漫配對模式：" + pairModeId);

    const opts = options || {};
    const pool = getEntriesInSeries(opts.series || DEFAULT_SERIES);
    if (!pool.length) throw new Error("動漫作品沒有可用題目");

    const count = Math.min(Math.max(1, pairCount), pool.length);
    const selected = shuffle(pool).slice(0, count);
    const sideA = mode.sides[0];
    const sideB = mode.sides[1];

    const cards = [];
    selected.forEach((entry) => {
      const picDisplay =
        entry.picKind === "symbol"
          ? "symbol"
          : entry.picKind === "img"
            ? "img"
            : "pic";
      cards.push({
        pairKey: entry.key,
        side: sideA,
        text: sideA === "audio" ? "" : entry[sideA],
        kindLabel: mode.sideLabels[sideA],
        display: sideA === "pic" ? picDisplay : "text",
        voiceText: entry.tts || entry.hira,
        voiceKey: entry.key,
        voicePack: "anime",
        label: entry.label,
        picSub: sideA === "pic" ? entry.picSub || "" : "",
      });
      cards.push({
        pairKey: entry.key,
        side: sideB,
        text: sideB === "audio" ? "" : entry[sideB],
        kindLabel: mode.sideLabels[sideB],
        display: sideB === "pic" ? picDisplay : "text",
        voiceText: entry.tts || entry.hira,
        voiceKey: entry.key,
        voicePack: "anime",
        label: entry.label,
        picSub: sideB === "pic" ? entry.picSub || "" : "",
      });
    });

    return shuffle(cards);
  }

  return {
    ENTRIES,
    SERIES,
    DEFAULT_SERIES,
    PAIR_MODES,
    getEntriesInSeries,
    buildDeck,
  };
})();
